import org.apache.hadoop.fs.viewfs.RegexMountPointResolvedDstPathReplaceInterceptor;
public class FunctionUse9712 {
public void funcUse() {
RegexMountPointResolvedDstPathReplaceInterceptor regexmountpointresolveddstpathreplaceinterceptor = new RegexMountPointResolvedDstPathReplaceInterceptor();
regexmountpointresolveddstpathreplaceinterceptor.getSrcRegexPattern();
}
}