import org.apache.hadoop.fs.viewfs.RegexMountPointResolvedDstPathReplaceInterceptor;
public class FunctionUse9707 {
public void funcUse() {
RegexMountPointResolvedDstPathReplaceInterceptor regexmountpointresolveddstpathreplaceinterceptor = new RegexMountPointResolvedDstPathReplaceInterceptor();
regexmountpointresolveddstpathreplaceinterceptor.interceptResolvedDestPathStr(null);
}
}